FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore webserver/webserver.csproj
RUN dotnet publish webserver/webserver.csproj \
    -c Release \
    -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build /app/publish .

RUN mkdir -p /app/log

EXPOSE 8080

ENTRYPOINT ["dotnet", "webserver.dll"]